### PR TITLE
Add syntax highlighting theme options; See: websharks/comment-mail#147

### PR DESCRIPTION
**Pull request by kristineds**
Add syntax highlighting theme options; 
-  Creating new config. option under: ​**Dashboard → Comment Mail → Config. Options → Template-Related Settings**
- Default syntax theme is `monokai`

See: websharks/comment-mail#147

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting Pull Request for Comment Mail LITE to add syntax theme dropdown options under Template-Related Settings

**Comment by jaswsinc** [comment]
@kristineds Same thing in this one. Take a look at my comment here please: https://github.com/websharks/comment-mail-pro/pull/24#issuecomment-152001603

**Comment by kristineds** [comment]
@jaswsinc @raamdev Updated changes and merged to `000000-dev` branch. See:https://github.com/websharks/comment-mail/commit/8d9b1fd819f48d4542ef45107d86bce6c8d47b02  :)

**Comment by kristineds** [comment]
@jaswsinc Submitting PR for CM Lite, https://github.com/websharks/comment-mail/commit/4df8f6b3e7c224a364b1769b1016bece280a93f7

**Comment by raamdev** [comment]
@jaswsinc I reviewed this and it looks good to me.

**Comment by jaswsinc** [comment]
@kristineds In the lite variation, [this line](https://github.com/websharks/comment-mail/blob/feature/147/comment-mail/plugin.inc.php#L444) should be written as:

```php
'template_syntax_theme',
```

_because we are just listing this option key itself in the array of pro-only option keys._

---

What you have now:

```php
'template_syntax_theme' => 'monokai',
```

should be moved to [this line](https://github.com/websharks/comment-mail/blob/feature/147/comment-mail/plugin.inc.php#L733) instead please.

**Comment by kristineds** [comment]
@jaswsinc Good catch! I must have been sleepcoding. Submitting updated code for the template syntax for CM Lite. :) https://github.com/websharks/comment-mail/commit/e0e5e37af8b7dd0853746ca9b88ded54d870b5b6

**Comment by jaswsinc** [comment]
Merged. Thanks @kristineds! Really appreciate your time on this.

**Pull request merged**
