### PR TITLE
Fix spelling mistake in email template; See: websharks/comment-mail#208

### PR DESCRIPTION
**Pull request by kristineds**
Fix spelling mistake in email template; 

- If selected, "yes, replies to my comment"
screen shot 2016-01-22 at 5 53 41 pm

- If selected, "yes, all comments/replies"
screen shot 2016-01-22 at 5 56 25 pm

See: websharks/comment-mail#208

### CODE REVIEW

**Comment by jaswsinc** [comment]
@kristineds Nice! 

Please fix the indentation in the template file; i.e., inside `[else]` should be indented to improve clarity for any site owner that is working with these templates in an effort to customize them.

**Comment by kristineds** [comment]
> Please fix the indentation in the template file; i.e., inside [else] should be indented to improve clarity for any site owner that is working with these templates in an effort to customize them.

@jaswsinc Like this? https://github.com/websharks/comment-mail/commit/9ac7d63514af3f24972436783cc9039f6561fb63

_Sorry for the multiple commits. Something weird was happening when I tried editing the file. Looks alright on the editor but when I push the changes, the indentation doesn't follow._

**Comment by jaswsinc** [comment]
> @jaswsinc Like this? 9ac7d63

Perfect. That looks great! Thank you very much :-)

**Comment by jaswsinc** [comment]
@raamdev This looks ready to merge.

**Comment by raamdev** [comment]
**Comment Mail v160213** has been released and includes changes from this GitHub Issue. See the [release announcement](http://comment-mail.com/comment-mail-v160213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#214).

**Pull request closed without merging**
