### PR TITLE
Add new option key `check_blacklist`; See: websharks/comment-mail#179

### PR DESCRIPTION
**Pull request by kristineds**
Add new option key `check_blacklist`; 

- Declare option key as a new class property and set the property value
- Only check blacklist if `$this->check_blacklist` is true

See: websharks/comment-mail#179

### CODE REVIEW

**Comment by jaswsinc** [comment]
@raamdev This looks ready to merge.

**Comment by raamdev** [comment]
@jaswsinc I don't see how this is configurable or how it is used by the subscription inserter routines... shouldn't that work go into this PR before merging?

**Comment by jaswsinc** [comment]
@raamdev See https://github.com/websharks/comment-mail/issues/179#issuecomment-169364819

This change allows us to later come back and update the StCR importer in ways that allow for the blacklist check to be disabled (or configured in some other area) during the insertion/import of subscribers.

I think it is safe to merge this in now, as it is merely allows for a new flag to be passed to the `sub_inserter()` class that tells it to disable `check_blacklist` in certain cases. The default value remains as it was. The blacklist is checked by default.

**Comment by raamdev** [comment]
> This change allows us to later come back and update the StCR importer in ways that allow for the blacklist check to be disabled (or configured in some other area) during the insertion/import of subscribers.

I guess I'm just wondering why all that work doesn't just go into this PR... :smile: I thought we were trying to avoid multiple PRs for each GitHub issue.

**Comment by jaswsinc** [comment]
It's fine with me if it does, but I see this as almost a separate issue; i.e., it is an enhancement which makes something else, somewhat unrelated (having to do with StCR) possible later.

**Comment by kristineds** [comment]
@jaswsinc I posted my comment [here](https://github.com/websharks/comment-mail/issues/179#issuecomment-171898553). If you could provide the outline for the `sub_inserter{}` class, I'll submit the PR for it. :smile:

**Comment by raamdev** [comment]
> It's fine with me if it does, but I see this as almost a separate issue; i.e., it is an enhancement which makes something else, somewhat unrelated (having to do with StCR) possible later.

Oh, I see. Thank you for clarifying. I agree, this can be merged now and the other work submitted in a separate PR. I'll merge this in shortly. Thank you.

**Pull request closed without merging**
