### PR TITLE
UI Enhancement; updating plugin title. See: websharks/comment-mail#131

### PR DESCRIPTION
**Pull request by kristineds**
Closes websharks/comment-mail#131

### CODE REVIEW

**Comment by raamdev** [comment]
Reviewed. Looks good to me!

**Comment by jaswsinc** [comment]
For the Lite version, can you check and see what it looks like with `Lite` instead of `Pro` :-) If it's too jumbled we can just exclude this from the Lite version.

**Comment by kristineds** [comment]
> can you check and see what it looks like with Lite instead of Pro 
Ha! Sorry. Was so used to submitting PRs for both Pro and Lite. That has been changed. :)

**Comment by jaswsinc** [comment]
haha.. No worries. Can you post a screenshot of what this looks like for me?

**Comment by raamdev** [comment]
> For the Lite version,

Ha, I totally missed that too.

**Comment by kristineds** [comment]
screen shot 2015-07-30 at 2 49 30 am

**Comment by raamdev** [comment]
> we can just exclude this from the Lite version.

I would just exclude the superscript from the Lite version altogether--adding `Lite` is too jumbled IMO.

**Comment by jaswsinc** [comment]
Thank you :-) Yep, that looks a bit hard to read with the extra letter. Thoughts on this? I say we could just exclude this from the Lite version. It works great for the Pro copy though.

**Comment by jaswsinc** [comment]
> I would just exclude the superscript from the Lite version altogether--adding Lite is too jumbled IMO.

Copy that.

**Pull request closed without merging**
