### PR TITLE
Adding RVE instructions. See: websharks/comment-mail#123

### PR DESCRIPTION
**Pull request by Reedyseth**
Restore assignment of $replies_via_email_enable.

Closes websharks/comment-mail#123

### CODE REVIEW

**Comment by Reedyseth** [comment]
@jaswsinc Done 6bef077f1d4877d7c6eebe1691ab5ed3fe3272bc !

**Comment by Reedyseth** [comment]
Also done for pro version.

**Comment by raamdev** [comment]
Reviewed. Looks good to me!

**Comment by jaswsinc** [comment]
Merged. Thank you!!

**Comment by Reedyseth** [comment]
Great, thank you !

**Pull request merged**
