### PR TITLE
Add WPML support

### PR DESCRIPTION
**Pull request by IvanRF**
See https://wpml.org/documentation/support/language-configuration-files/

It allows to translate fields and templates content to multiple languages.

### CODE REVIEW

**Comment by IvanRF** [comment]
@raamdev this same code I sent to StCR is needed in this plugin: [Mail messages localization support for WPML](https://github.com/stcr/subscribe-to-comments-reloaded/pull/121/files).
It changes the language to use on the mail based on the language from the post. Currently, all mails are sent in the WP default language when using WPML.

It should be included before any option/content for the mail is loaded. Where in code is that?

**Comment by IvanRF** [comment]
You can see the `wpml-config.xml` in action here: [English](ivanrf.com/en/asus-smart-gesture-and-windows-10/#respond) | [Spanish](http://ivanrf.com/asus-smart-gesture-y-windows-10/#respond)

**Comment by raamdev** [comment]
@IvanRF Thanks so much for the PR! I've tagged this `ready for review` and will come back around to this when I get a chance to test this. :-)

**Comment by IvanRF** [comment]
@raamdev based on what you showed me on https://github.com/websharks/comment-mail/issues/249, Pro version has more fields. So, the keys corresponding to those fields should be added too in this file.

**Pull request closed without merging**
