### PR TITLE
Improve Dashboard Notice; See: websharks/comment-mail#163

### PR DESCRIPTION
**Pull request by kristineds**
Improve Dashboard notice; 

- Improve "Upgrading from StCR" message:
- Add "Comment Mail is disabled" message

Improve CM Dashboard notice

See: websharks/comment-mail#163

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting PR for Comment Mail Lite to Improve Dashboard Notice. 

Btw, since the link for _"Click here to review the StCR -> Comment Mail import process"_ redirects the user to the Import/Export page, won't that be confusing to users as this feature is only available for Comment Mail Pro? :)

**Comment by jaswsinc** [comment]
@kristineds Great!

> won't that be confusing to users as this feature is only available for Comment Mail Pro? :)

While the import/export routines are pro-only, we make one exception for StCR. The StCR importer will be available on that page (and only that one importer) whenever you have just the lite version.

**Comment by jaswsinc** [comment]
@raamdev Before you merge this please see: https://github.com/websharks/comment-mail/issues/163#issuecomment-160878246

**Comment by raamdev** [comment]
@kristineds Merged! Thank you.

**Pull request closed without merging**
