### PR TITLE
Improve Default Comment Reply Notification Template

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/comment-mail#77

### CODE REVIEW

**Comment by raamdev** [comment]
Note: This is still a work in progress...

**Comment by raamdev** [comment]
@jaswsinc This is ready for a review when you get a chance. See also the Comment Mail Pro PR, which includes changes to the Advanced Templates: https://github.com/websharks/comment-mail-pro/pull/35

**Comment by jaswsinc** [comment]
> so instead they will use the comment form that is visible thinking they're replying to the comment they just read, when in fact they're just posting a new top-level comment responding to the whole post.

I see! That's great. I would not have thought of that scenario had you not pointed it out. I also see why you chose to use `get_permalink()` instead of [`get_comment_reply_link()`](https://github.com/WordPress/WordPress/blob/a027edc277e079f813928873a315429361f4e93e/wp-includes/comment-template.php#L1503).

**Comment by jaswsinc** [comment]
@raamdev While you're working in these files, would you mind changing lines like [this one](https://github.com/websharks/comment-mail/blob/8a6005c8b0f272cd15027c2345671526a22139cb/comment-mail/includes/templates/type-s/email/comment-notification/message.php#L16) from `\stdClass` to `\WP_Comment` please?

**Comment by jaswsinc** [comment]
That's all I've got. The rest of this PR looks great to me.

**Comment by raamdev** [comment]
@jaswsinc writes...
> You can remove the square brackets from the [comment_reply_to_own_comment] array key to make it so this particular variable can only be used in snippet conditionals and never as a replacement code itself; i.e., it is only a boolean flag, not a string value.

Awesome! I did not know that. Great idea. 

> In the clip_deep() and mid_clip_deep() methods, you'll want to change the 3s to the new number of characters in [...], which is now 5 instead of 3. Also, the minimum $max_length of 4 should now be 6.

Oh! Thanks so much for catching that. I should've taken the time to review the entire methods before modifying them. :wink: 

> In lines like this one, I suggest we move the trailing whitespace from the translatable string Reply to, and instead add the white space as a part of the concatenation that is hard-coded.

Another great catch. I knew there was something wrong with adding the space to the translation string, but at the time my brain couldn't figure out what. Maybe it was just after thinking about that damn rattlesnake Elvis riddle. :laughing: 

---

All of the above have been fixed in https://github.com/websharks/comment-mail/commit/02976d2fe0b12c1dfe2c1e93465596a3a93d46ec (Lite) and https://github.com/websharks/comment-mail-pro/commit/63e0772e54742c9ec431a318d465fd6a5fd6d286 (Pro). Another quick review of my changes there would be appreciated. :-)

**Comment by raamdev** [comment]
@jaswsinc writes...
> While you're working in these files, would you mind changing lines like this one from \stdClass to \WP_Comment please?

I updated everything in the `includes/templates/` directory that should be using `\WP_Comment` instead of `\stdClass`. If you can review https://github.com/websharks/comment-mail/commit/7d6995aed2122c978dc9b52c81fcf1a5dddfdf8e (Lite) and https://github.com/websharks/comment-mail-pro/commit/3015509e97966c5ad81ab7914373833399b5ef13 (Pro) for me, that would be great. :smile:

**Comment by jaswsinc** [comment]
> after thinking about that damn rattlesnake Elvis riddle.

lol

**Comment by jaswsinc** [comment]
@raamdev Other than the one remaining `3` the rest of your hard work looks great to me.

**Pull request closed without merging**
